name: IPTV

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 */2 * * *'  # 每2小时运行一次

jobs:
  update-iptv:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置环境
      run: |
        echo "SOURCE_URL=https://raw.githubusercontent.com/tianli1680/iptv/refs/heads/main/IPTV.m3u" >> $GITHUB_ENV
        echo "UPDATE_TIME=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV
        
    - name: 下载并处理IPTV数据
      run: |
        # 下载源数据
        curl -s "${{ env.SOURCE_URL }}" -o iptv_source.txt
        
        # 创建输出目录
        mkdir -p output
        
        # 提取央视频道 - CCTV (IPTV1)
        echo "# CCTV频道列表 - 更新时间: ${{ env.UPDATE_TIME }}" > output/IPTV1.m3u
        grep -A 10 "央视" iptv_source.txt | grep -E "(CCTV|央视)" | grep -v "CCTV-MCP" >> output/IPTV1.m3u
        
        # 提取央视频道 - CCTV-MCP (IPTV2)
        echo "# CCTV-MCP频道列表 - 更新时间: ${{ env.UPDATE_TIME }}" > output/IPTV2.m3u
        grep -A 10 "央视" iptv_source.txt | grep "CCTV-MCP" >> output/IPTV2.m3u
        
        # 提取卫视频道 (IPTV3)
        echo "# 卫视频道列表 - 更新时间: ${{ env.UPDATE_TIME }}" > output/IPTV3.m3u
        grep -A 10 "卫视" iptv_source.txt | grep -v "央视" >> output/IPTV3.m3u
        
        # 提取体育频道 (IPTV4)
        echo "# 体育频道列表 - 更新时间: ${{ env.UPDATE_TIME }}" > output/IPTV4.m3u
        grep -A 10 "体育" iptv_source.txt >> output/IPTV4.m3u
        
        # 生成合并的播放列表
        cat output/IPTV1.m3u output/IPTV2.m3u output/IPTV3.m3u output/IPTV4.m3u > output/all_channels.m3u
        
    - name: 验证生成的文件
      run: |
        echo "=== 生成的文件列表 ==="
        ls -la output/
        echo ""
        echo "=== 各频道数量统计 ==="
        echo "IPTV1 (CCTV): $(grep -c "EXTINF" output/IPTV1.m3u || true) 个频道"
        echo "IPTV2 (CCTV-MCP): $(grep -c "EXTINF" output/IPTV2.m3u || true) 个频道"
        echo "IPTV3 (卫视): $(grep -c "EXTINF" output/IPTV3.m3u || true) 个频道"
        echo "IPTV4 (体育): $(grep -c "EXTINF" output/IPTV4.m3u || true) 个频道"
        echo "总计: $(grep -c "EXTINF" output/all_channels.m3u || true) 个频道"
        
    - name: 提交更改
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/
        git commit -m "自动更新IPTV频道列表 - ${{ env.UPDATE_TIME }}" || exit 0
        git push
        
    - name: 上传生成的文件
      uses: actions/upload-artifact@v4
      with:
        name: iptv-playlists
        path: output/
        retention-days: 7
        
    - name: 发送通知
      if: always()
      run: |
        echo "IPTV频道更新任务完成!"
        echo "更新时间: ${{ env.UPDATE_TIME }}"
        echo "源URL: ${{ env.SOURCE_URL }}"
